### ISSUE TITLE
Interesting framework - validation question

### ISSUE THREAD

**Issue by tynor88** [hartmanns/ScaffoldR#1]
Hi

Looks like an interesting framework - I am going to give it a shot once it is out.

In your example you have a ValidateMakeCoffee: 

```
public class ValidateMakeCoffee : AbstractValidator<MakeCoffee>
{
    public ValidateMakeCoffee()
    {
        RuleFor(coffee => coffee.Strength)
                    .NotEmpty()
                    .GreaterThan(0)
                    .LessThanOrEqualTo(10);
    }
}
```

but you don't call it anywhere. Where would you call this validation?

**Comment by janhartmann** [comment]
Hi,

Thanks for interest. :-) 

Sorry for the lack of documentation so far, I am currently working on it. Here is some information on how its working (until documentation is completely done):

Before any command/query handler is executed (either by depending on the `IHandleCommand<TCommand>` or by using the mediators `IProcessCommands` and `IProcessQueries`) the command goes though a few decorators:

1) The command/query is checked for null
2) The command/query is scoped in a new lifetime scope
3) The command/query is validated, if an `AbstractValidator<T>` of the type is found in the IoC container. If the validation fails, there will be thrown an exception with the errors
4) The command/query handler is found in the IoC container and is invoked
5) If the command/query handler has an `[RaiseEvent]` attribute on it, it will after execution of the command notify all event handlers that the command/query has executed.

It is also possible to run the validation on any given time, by depending on the interface `IProcessValidation` and use its `Validate(ICommand command)` or its `Validate(IQuery<TResult> query)` methods.

With this method, you are able to hook the validators directly in the `ModelState.IsValid` check:

``` cs
FluentValidationModelValidatorProvider.Configure(provider => {
    provider.ValidatorFactory = new SimpleInjectorValidatorFactory(container);
    provider.AddImplicitRequiredValidator = false;
});
```

Which means you in your controller can do the following to catch the error before the validation is run again before executing:

``` cs
[HttpPost]
public ActionResult Create(MakeCoffee cup)
{
    if (ModelState.IsValid)
    {
        // Use the mediator to execute the command
        _commands.Execute(cup);
        return Redirect(...);
    }

    // Now we have the model state, so lets display 
    // the page again and show what errors we had
    return View();
}
```

There was a bit on the flow of commands and queries. I will work on the very details in the upcoming documentation :-)

Jan

**Comment by janhartmann** [comment]
P.s are you a fellow Dane? ;-)

**Comment by tynor88** [comment]
Sounds good. I will definitely give it a shot, when you release it.

Another question: Is it _only_ for ASP.NET MVC projects or could you use it in a ASP.NET WebApi 2 project aswell?

Oh yeah, even one from "Dobbelt A" :-)

**Comment by janhartmann** [comment]
I think the version 1.0 is out later today. Just going to arrange NuGet now. 

Its not limited to MVC, it works with WebAPI and WCF as well. Just configure the containers "DefaultScope" and everything should work out just fine. Even for console applications :-)

Cool, me too.. :-)
